### PR TITLE
fix: nostr key option

### LINKED ISSUE #4: Server does not respond if no nostr key is set
Debug if failure on start or later

### PR DESCRIPTION
**Pull request by thesimplekid**
fix #4

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -72,9 +72,14 @@ async fn main() -> anyhow::Result<()> {
...
 
-    let nostr_pubkey = plugin
-        .option("clnurl_nostr_pubkey")
-        .map(|v| v.as_str().expect("Option is string").to_owned());
+    let nostr_pubkey = match plugin.option("clnurl_nostr_pubkey") {
+        Some(Value::String(pubkey)) => Some(pubkey),
+        Some(Value::OptString) => None,
+        _ => {
+            // Something unexpected happened
+            None
```
Comment (elsirion) [inline src/main.rs:80]: ~Did you figure out why we got a different answer? Sounds like a potential CLN bug that might be worth opening upstream.~ Never mind, it's described in https://github.com/elsirion/clnurl/issues/4#issuecomment-1474546866

**Review by elsirion — APPROVED** [review]
